  services:
    node1:
      image: ubuntu:24.04
      container_name: nnode01
      hostname: node01
      ports:
        - "8481:8480"
        - "9871:9870"
        - "8081:8088"
      command: sleep infinity
      volumes:
        - ./shared:/shared
      networks:
        - cluster-network

    node2:
      image: ubuntu:24.04
      container_name: nnode02
      hostname: node02
      ports:
        - "8482:8480"
        - "9872:9870"
        - "8082:8088"
      command: sleep infinity
      volumes:
        - ./shared:/shared
      networks:
        - cluster-network

    node3:
      image: ubuntu:24.04
      container_name: nnode03
      hostname: node03
      ports:
        - "8483:8480"
        - "9873:9870"
        - "8083:8088"
      command: sleep infinity
      volumes:
        - ./shared:/shared
      networks:
        - cluster-network

    node4:
      image: ubuntu:24.04
      container_name: nnode04
      hostname: node04
      ports:
        - "8484:8480"
        - "9874:9870"
        - "8084:8088"
      command: sleep infinity
      volumes:
        - ./shared:/shared
      networks:
        - cluster-network

    node5:
      image: ubuntu:24.04
      container_name: nnode05
      hostname: node05
      ports:
        - "8485:8480"
        - "9875:9870"
        - "8085:8088"
      command: sleep infinity
      volumes:
        - ./shared:/shared
      networks:
        - cluster-network

  networks:
    cluster-network:
      driver: bridge
